import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-screen h-screen bg-gradient-to-b from-blue-50 to-red-100 overflow-hidden`}
      >
        <div className="px-4 sm:px-4 md:px-12 lg:px-20 xl:px-48 h-full py-10 flex items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
